# Simple Cloud Build configuration for RAG System
# Builds all services with latest tag

timeout: '3600s'

options:
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'rag-system'

steps:
  # Build shared library first
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-shared'
    args: ['mvn', 'clean', 'install', '-pl', 'rag-shared', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'

  # Build and package rag-auth-service
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-auth'
    waitFor: ['build-shared']
    args: ['mvn', 'clean', 'package', '-pl', 'rag-auth-service', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-auth'
    waitFor: ['build-auth']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-auth-service:latest'
      - '-f'
      - 'rag-auth-service/Dockerfile'
      - '.'

  # Build and package rag-document-service
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-document'
    waitFor: ['build-shared']
    args: ['mvn', 'clean', 'package', '-pl', 'rag-document-service', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-document'
    waitFor: ['build-document']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-document-service:latest'
      - '-f'
      - 'rag-document-service/Dockerfile'
      - '.'

  # Build and package rag-embedding-service
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-embedding'
    waitFor: ['build-shared']
    args: ['mvn', 'clean', 'package', '-pl', 'rag-embedding-service', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-embedding'
    waitFor: ['build-embedding']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-embedding-service:latest'
      - '-f'
      - 'rag-embedding-service/Dockerfile'
      - '.'

  # Build and package rag-core-service
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-core'
    waitFor: ['build-shared']
    args: ['mvn', 'clean', 'package', '-pl', 'rag-core-service', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-core'
    waitFor: ['build-core']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-core-service:latest'
      - '-f'
      - 'rag-core-service/Dockerfile'
      - '.'

  # Build and package rag-admin-service
  - name: 'maven:3.9-eclipse-temurin-21'
    id: 'build-admin'
    waitFor: ['build-shared']
    args: ['mvn', 'clean', 'package', '-pl', 'rag-admin-service', '-am', '-DskipTests']
    env: ['MAVEN_OPTS=-Xmx2g']
    volumes:
      - name: 'maven-repo'
        path: '/root/.m2'
  
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-admin'
    waitFor: ['build-admin']
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-admin-service:latest'
      - '-f'
      - 'rag-admin-service/Dockerfile'
      - '.'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-auth-service:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-document-service:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-embedding-service:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-core-service:latest'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/rag-admin-service:latest'
