# Docker Compose Override for Development
# This file provides development-specific overrides
# Automatically loaded with docker-compose up

services:
  # Development overrides for microservices
  rag-gateway:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-gateway/logs:/app/logs

  rag-auth:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-auth-service/logs:/app/logs

  rag-document:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-document-service/logs:/app/logs
      - ./rag-document-service/storage:/app/storage

  rag-embedding:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-embedding-service/logs:/app/logs

  rag-core:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-core-service/logs:/app/logs

  rag-admin:
    environment:
      - LOGGING_LEVEL_COM_ENTERPRISE_RAG=DEBUG
    volumes:
      - ./rag-admin-service/logs:/app/logs

  # Development tools
  redis:
    ports:
      - "8001:8001"  # RedisInsight UI for development

  # Add pgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rag-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@enterprise-rag.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - rag-network

volumes:
  pgadmin_data: