server:
  port: 8081

spring:
  application:
    name: rag-auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_auth
    username: ${DB_USERNAME:rag_user}
    password: ${DB_PASSWORD:rag_password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
  
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:YourVerySecureJWTSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:3600}    # 1 hour
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800} # 7 days

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging
logging:
  level:
    com.enterprise.rag: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/rag_auth
  
  redis:
    host: redis

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

jwt:
  secret: TestSecretKeyForJWTThatIsAtLeast256BitsLongForHS256Algorithm